### ISSUE TITLE
Ability to sort columns in SPEC System on SPECS tab

### ISSUE THREAD

**Issue by evelinec1** [iotexpert/specsystem#63]
Add ability to sort columns (ascending or descending) in SPEC System on SPECS tab (as current setting in CTS allows)

**Comment by ggearing** [comment]
In refactor, also replace django query/serializer with raw_sql utilities and the query below.

select 
	s.num,
	s.ver,
	s.title,
	s.doc_type_id doc_type,
	s.department_id department,
	s.keywords,
	s.state,
	u.username created_by,
	convert(varchar(50),s.create_dt at time zone 'utc', 127) create_dt,
	convert(varchar(50),s.mod_ts at time zone 'utc', 127) mod_ts,
	s.jira,
	s.anon_access,
	s.reason,
	convert(varchar(50),s.approved_dt at time zone 'utc', 127) approved_dt,
	case when s.state = 'Active' and dt.sunset_interval is not null then 
		case when s.sunset_extended_dt is not null 
			then convert(varchar(50),dateadd(second, dt.sunset_interval/1000/1000, s.sunset_extended_dt) at time zone 'utc', 127) 
			else convert(varchar(50),dateadd(second, dt.sunset_interval/1000/1000, s.approved_dt) at time zone 'utc', 127)
		end
	end sunset_dt,
	s.location_id,
	(select convert(varchar(50),min(h.mod_ts) at time zone 'utc', 127)  from spec_hist h where h.spec_id = s.id and h.change_type = 'Submit') first_submit_dt ,
	(select convert(varchar(50),max(h.mod_ts) at time zone 'utc', 127)  from spec_hist h where h.spec_id = s.id and h.change_type = 'Submit') last_submit_dt ,
	(select count(*) from spec_hist h where h.spec_id = s.id and h.change_type = 'Reject') reject_cnt ,
	(select count(*) from spec_hist h where h.spec_id = s.id and h.change_type = 'Admin Update') admin_upd_cnt ,
	case when s.state = 'Signoff' then 
		(	select string_agg(concat(ss.role_id,':',au.username), ', ') 
			from spec_sig ss 
			inner join auth_user au on au.id = ss.signer_id
			where ss.spec_id = s.id and ss.signed_dt is null)
	end missing_sigs 
from spec s
left join auth_user u on u.id = s.created_by_id
left join doc_type dt on dt.name = s.doc_type_id
