### ISSUE TITLE
Add additional data to SPECS tab and download file

### ISSUE THREAD

**Issue by evelinec1** [iotexpert/specsystem#64]
Add additional data to SPECS tab and download file for Doc Control to use for reporting and metrics.

To display add:
* Last submit date (only shows values if State = Signoff)
* Outstanding signoffs (only shows values if State = Signoff)

To download add:
* First submit date
* Last submit date
* # times document rejected (count)
* # of times admin change (count)
* Outstanding signoffs

**Comment by ggearing** [comment]
Verified by Eveline
